// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/graph/code": {
            "get": {
                "description": "图片验证码",
                "consumes": [
                    "image/jpeg"
                ],
                "tags": [
                    "图片验证码模块"
                ],
                "summary": "图片验证码",
                "responses": {}
            }
        },
        "/health": {
            "post": {
                "description": "应用存活接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康模块"
                ],
                "summary": "应用存活接口",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PongArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "$ref": "#/definitions/server.PongVOResult"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "获取用户信息接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息接口",
                "parameters": [
                    {
                        "description": "账号",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录信息",
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginVOResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.PongArgs": {
            "type": "object",
            "required": [
                "say"
            ],
            "properties": {
                "say": {
                    "type": "string"
                }
            }
        },
        "server.PongVO": {
            "type": "object",
            "properties": {
                "res": {
                    "type": "string"
                }
            }
        },
        "server.PongVOResult": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "状态短语",
                    "type": "string"
                },
                "result": {
                    "description": "数据结果集",
                    "$ref": "#/definitions/server.PongVO"
                }
            }
        },
        "server.UserLoginArgs": {
            "type": "object",
            "properties": {
                "image_code": {
                    "type": "string"
                },
                "image_token": {
                    "type": "string"
                },
                "lt": {
                    "type": "string",
                    "example": ""
                },
                "mobile": {
                    "type": "string",
                    "example": "18800011122"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "server.UserLoginVO": {
            "type": "object",
            "properties": {
                "st": {
                    "type": "string",
                    "example": ""
                },
                "token": {
                    "type": "string",
                    "example": "TGT-FwLZ7dHoHepX4zMgVdB3WGmqZ94rMsK4"
                }
            }
        },
        "server.UserLoginVOResult": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "状态短语",
                    "type": "string"
                },
                "result": {
                    "description": "数据结果集",
                    "$ref": "#/definitions/server.UserLoginVO"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"{{scheme}}"},
	Title:            "budd",
	Description:      "budd",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
